apiVersion: v2
name: nginx
description: A Helm chart for NGINX deployment on Kubernetes
type: application
version: 1.0.0
appVersion: "1.25.3"
home: https://nginx.org
sources:
  - https://github.com/nginx/nginx
keywords:
  - nginx
  - web
  - server
  - http
maintainers:
  - name: Your Name
    email: your.email@example.com