# helm-chart/templates/managedcertificate.yaml (GKE-specific)
{{- if and .Values.ingress.enabled (hasKey .Values.ingress.annotations "networking.gke.io/managed-certificates") }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ingress.annotations "networking.gke.io/managed-certificates" }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
{{- end }}