name: Deploy NGINX to GKE

on:
  push:
    branches: [ main ]
    paths:
      - 'nginx-chart/**'
      - '.github/workflows/deploy-nginx.yml'
  workflow_dispatch:

env:
  PROJECT_ID: "regal-spark-464611-v3"
  CLUSTER_NAME: nginx-helm-chart
  # GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: "us-central1-a"
  RELEASE_NAME: nginx-release
  CHART_PATH: ./nginx-chart

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: Deploy Helm chart
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace default \
            --create-namespace

            
